# Nome della action
name: Deploy React App to GH pages

# Evento che triggera la action
on: 
  push:
    branches: [ main ]

# Setup della action 
jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Codice custom
      - run: npm ci
      - run: npm test
      - run: nmp run build

      ## Presa dal marketplace
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
